services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  local_pgdata:
