import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import RootProvider from './rootProvider'
import CustomAvatar from '@/components/other/CustomAvatar'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootProvider>
          <header className="sticky top-0 z-30 flex justify-end flex h-16 border-0 p-4 h-auto">
            <CustomAvatar />
          </header>
          {children}
        </RootProvider>
      </body>
    </html>
  )
}
